name: Deploy Dev from Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to deploy (ex: v1.45.2)"
        required: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tags
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch --tags

          # Create the input tag on the current commit
          git tag "${{ github.event.inputs.tag }}"

          # Create the unstable tag based on the input tag
          NEW_TAG="${{ github.event.inputs.tag }}-unstable"
          git tag "$NEW_TAG" "${{ github.event.inputs.tag }}"

          # Push both tags
          git push origin "${{ github.event.inputs.tag }}"
          git push origin "$NEW_TAG"

      - name: Deploy to Vercel (Dev)
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_Y6x0SGC6fmsUzyy6GYi5bRDE6YBJ" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"meta\": {
                \"version\": \"${{ github.event.inputs.tag }}\",
                \"env\": \"development\"
              }
            }"
