name: Deploy Dev from Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to deploy (ex: 1.45.2)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dev release tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch --tags

          NEW_TAG="${{ github.event.inputs.tag }}-unstable"
          git tag "$NEW_TAG" "${{ github.event.inputs.tag }}"
          git push origin "$NEW_TAG"

      - name: Deploy to Vercel (Dev)
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_xxxxx" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "meta": {
                "version": "${{ github.event.inputs.tag }}-alpha",
                "env": "development"
              }
            }'
